apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - name: web
          image: web
          imagePullPolicy: Never
          args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: CompanyDB
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_PORT
              value: "3307"
            - name: DB_USER
              value: Aaron
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      volumes:
        - configMap:
            name: web-cm0
          name: web-cm0
