# Generated by Django 4.2.5 on 2023-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('Site', models.CharField(max_length=255)),
                ('PC_tag', models.CharField(db_column='PC-Tag', max_length=255)),
                ('MAC', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=255)),
                ('Local_IP', models.CharField(max_length=255)),
                ('Patch_V2', models.CharField(max_length=255)),
                ('vpncfg_nc', models.CharField(max_length=255)),
                ('x_scr', models.CharField(max_length=255)),
                ('x_zm', models.CharField(max_length=255)),
                ('ldap_ipa2', models.CharField(max_length=255)),
                ('ldaprs', models.CharField(max_length=255)),
                ('chmd_ipa', models.CharField(max_length=255)),
                ('incog', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Monitoring',
            },
        ),
    ]
